routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SystemConfigController;
use App\Http\Controllers\Admin\PackageTypeController;
use App\Http\Controllers\Admin\TruckController;
use App\Http\Controllers\Admin\TruckTypeController;
use App\Http\Controllers\Admin\ShipperController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\BookingController;
use App\Http\Controllers\Admin\TruckUnitController;
use App\Http\Controllers\Shipper\AddressController;
use App\Http\Controllers\Shipper\AuthController;
use App\Http\Controllers\Shipper\DasboardController;
use App\Http\Controllers\Shipper\ProductController;
use App\Http\Controllers\Shipper\ShipmentController;
use App\Http\Controllers\Shipper\MultipleShipmentController;
use App\Http\Controllers\Shipper\ShipmentDesignController;
use App\Http\Controllers\Shipper\ManageShipmentController;
use App\Http\Controllers\Shipper\SearchAvailableTruckController;
use App\Http\Controllers\Shipper\ManagerManagementController;
use App\Http\Controllers\Shipper\ChatController;
use App\Http\Controllers\Shipper\DahsboardNewController;
use App\Http\Controllers\Shipper\NotificationController;
use App\Http\Controllers\Shipper\InvoiceController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\Carrier\DriverController as CarrierDriverController;
use App\Http\Controllers\Carrier\VehicleController;
use App\Http\Controllers\Carrier\CarrierAuthController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::POST('send-mail/{id}',[ShipperController::class,'send_mail']);
Route::POST('driver_send_mail/{id}',[DriverController::class,'driver_send_mail']);
Route::get('shipper-comission/{key}',[InvoiceController::class, 'shipperCommisionInvoice']);

Route::get('/', function () {
    return view('home');
});
Route::get('testData',[DashboardController::class,'testData']);
Route::get('/carrier', function () {
    return view('carrier');
});

Route::get('/shipper-demo', function () {
    return view('shipper');
});
Route::get('/terms-and-conditions', function () {
	    return view('terms_conditions');
	});
Route::get('/privacy-policy', function () {
	    return view('privacy_policy');
	});
Route::get('/about-us', function () {
	    return view('about-us');
	});
Route::get('change/lang/{lang}',[WebsiteController::class, 'changeLang'])->name('change-lang');

Route::get('cron-availability-trash',[AuthController::class, 'cron_past_availability'])->name('cron-availability-trash');
Route::get('cron-booking-trash',[AuthController::class, 'cron_past_booking'])->name('cron-booking-trash');
Route::get('cron-scheduled-booking-trash',[AuthController::class, 'cron_past_booking_scheduled'])->name('cron-scheduled-booking-trash');
// Route::get('/', function(){
// 	return view('shipper.pages.home');
// });
Route::get('/privacy-policy',[DashboardController::class,'get_privacy']);
	Route::get('/terms-condition',[DashboardController::class,'get_terms_condition']);
	Route::get('/about-us',[DashboardController::class,'get_about']);
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard');
	Route::get('terms_condition',[DashboardController::class,'terms_condition_index'])->name('terms_condition');
	Route::post('terms_condition/submit',[DashboardController::class,'terms_condition'])->name('terms_condition.submit');
	Route::get('about_us',[DashboardController::class,'about_us_index'])->name('about_us');
	Route::get('about_us/submit',[DashboardController::class,'about_us'])->name('about_us.submit');
	Route::get('my_profile',[DashboardController::class,'my_profile'])->name('my_profile');
	
	
	Route::get('privacy_policy',[DashboardController::class,'privacy_policy_index'])->name('privacy_policy');
	Route::post('privacy_policy/submit',[DashboardController::class,'privacy_policy'])->name('privacy_policy.submit');

	Route::get('dashboard/chart',[DashboardController::class,'chart']);
	Route::post('status/change/{table}/{id}/{newstatus}', [DashboardController::class,'status'])->name('status');
	

	Route::get('users',[UserController::class,'index'])->name('users.index');
	
	Route::get('system/config',[SystemConfigController::class,'index'])->name('system.config');
	Route::post('system/config/submit',[SystemConfigController::class,'update'])->name('system.config.submit');
	Route::get('app/config',[SystemConfigController::class,'app'])->name('app.config');
	Route::post('app/config/submit',[SystemConfigController::class,'submit_app'])->name('app.config.submit');
	Route::get('system/section',[SystemConfigController::class,'index_system']);
	

	#PACKAGE_TYPE
	Route::group(['prefix' => 'package/type'], function () {
		Route::get('/{id?}', [PackageTypeController::class,'index'])->name('package.type.index');
		Route::post('submit', [PackageTypeController::class,'store'])->name('package.type.submit');
		Route::get('edit/{id}', [PackageTypeController::class,'edit'])->name('package.type.edit');
		Route::post('update/{id}', [PackageTypeController::class,'update'])->name('package.type.update');
		Route::delete('delete/{id}', [PackageTypeController::class,'destroy'])->name('package.type.delete');
	});

	#PRODUCT_UNIT
	Route::group(['prefix' => 'truck/unit'], function () {
		Route::get('/{id?}', [TruckUnitController::class,'index'])->name('truck.unit.index');
		Route::post('submit', [TruckUnitController::class,'store'])->name('truck.unit.submit');
		Route::get('edit/{id}', [TruckUnitController::class,'edit'])->name('truck.unit.edit');
		Route::post('update/{id}', [TruckUnitController::class,'update'])->name('truck.unit.update');
		Route::delete('delete/{id}', [TruckUnitController::class,'destroy'])->name('truck.unit.delete');
	});

	#TRUCK_CATEGORY
	Route::group(['prefix' => 'truck/category'], function () {
		Route::get('/{id?}', [TruckController::class,'index'])->name('truck.category.index');
		Route::post('submit', [TruckController::class,'store'])->name('truck.category.submit');
		Route::get('edit/{id}', [TruckController::class,'edit'])->name('truck.category.edit');
		Route::post('update/{id}', [TruckController::class,'update'])->name('truck.category.update');
		Route::delete('delete/{id}', [TruckController::class,'destroy'])->name('truck.category.delete');
		
	});

	#TRUCK_TYPE
	Route::group(['prefix' => 'truck/type'], function () {
		Route::get('/{id?}', [TruckTypeController::class,'index'])->name('truck.type.index');
		Route::post('submit', [TruckTypeController::class,'store'])->name('truck.type.submit');
		Route::get('edit/{id}', [TruckTypeController::class,'edit'])->name('truck.type.edit');
		Route::post('update/{id}', [TruckTypeController::class,'update'])->name('truck.type.update');
		Route::delete('delete/{id}', [TruckTypeController::class,'destroy'])->name('truck.type.delete');
		
	});

	#SHIPPER
	Route::group(['prefix' => 'shipper'], function(){
		Route::get('/', [ShipperController::class,'index'])->name('shipper.index');
		Route::get('view/{id}', [ShipperController::class,'view'])->name('shipper.view');
		Route::post('update/{id}', [ShipperController::class,'update'])->name('shipper.update');
		Route::post('approve/{id}/{status}', [ShipperController::class,'approveStatus'])->name('shipper.approve.status');
		Route::get('shipment/{id}', [ShipperController::class,'shipment']);
		Route::get('shipment_demo/{id}', [ShipperController::class,'demo_shipment']);
		Route::get('shipment-comm/{id}', [ShipperController::class,'commission_fee']);
		// Route::get('generate_invoice', [ShipperController::class,'generate_invoice']);
		Route::get('generate-invoice/{id}', [ShipperController::class,'get_invoice']);
		Route::get('view_profile/{id}', [ShipperController::class,'view_profile'])->name('shipper.view_profile');
		Route::get('shipment-detail/{id}', [ShipperController::class,'shipment_detail']);
		Route::get('shipment-search/{id}', [ShipperController::class,'shipment_search']);
		Route::post('shipment-search/public/{id}', [ShipperController::class,'publish_shipment']);
	});

	#DRIVER
	Route::group(['prefix' => 'driver'], function(){
		Route::get('/', [DriverController::class,'index'])->name('driver.index'); 
		Route::get('view/{id}', [DriverController::class,'view'])->name('driver.view');
		Route::get('view_load/{id}', [DriverController::class,'view_load'])->name('driver.view_load');
		Route::get('generate_invoice/{id}', [DriverController::class,'get_invoice']);
		// Route::get('view_load/{id}', [DriverController::class,'my_loads_demo'])->name('driver.my_loads_demo');
		Route::get('view_profile/{id}', [DriverController::class,'view_profile'])->name('shipper.view_profile');
		Route::post('update/{id}', [DriverController::class,'update'])->name('driver.update');
		Route::post('accept/{id}', [DriverController::class,'accepted'])->name('driver.accepted');
		Route::post('reject/{id}', [DriverController::class,'rejected'])->name('driver.rejected');
		Route::post('block/{id}/{status}', [DriverController::class,'blockStatus'])->name('driver.block.status');
		Route::post('change-permissions/{id}', [DriverController::class,'change_permission'])->name('driver.change-permissions');
		
	});

	#BOOKING
	Route::group(['prefix' => 'booking'], function(){
		Route::get('/', [BookingController::class,'index'])->name('booking.index'); 
		Route::delete('delete/{id}', [BookingController::class,'destroy'])->name('booking.delete');
		// Route::get('view/{id}', [DriverController::class,'view'])->name('driver.view');

app/Models/Shipper.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shipper extends Model
{
    use HasFactory;

 

}

app/Http/Controllers/Shipper/DahsboardController.php
<?php

namespace App\Http\Controllers\Shipper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DahsboardNewController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');
    }

    public function index(){
        return view('shipper.pages.home');
    }

    public function carrier_info($id)
    {
        echo '<pre>';print_r($id);die();
    }
}

app/Http/Controllers/Shipper/DahsboardNewController.php
<?php

namespace App\Http\Controllers\Shipper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DahsboardController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');
    }

    public function index(){
        return view('shipper.pages.home');
    }
}

app/Http/Controllers/Shipper/NotificationController.php
<?php

namespace App\Http\Controllers\Shipper;
use App\Models\Notification;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class NotificationController extends Controller
{
	public function index()
    {
        $user =Auth::user();

        Notification::where(['user_id' => $user->id])->update(['read_status' => '1']);
    	// $data = Notification::get();
    	// print_r($data);
    	// $columns = [
     //                    ['data' => 'id', 'name' => "id",'title' => __("S.No."),'width'=>'20px'], 
     //                    ['data' => 'user_id', 'name' => "user_id",'title' => __("User ID"),'width'=>'60px'], 
     //                    ['data' => 'title', 'name' => "title",'title' => __("Title"),'width'=>'60px'], 
     //                    ['data' => 'message', 'name' => "message",'title' => __("Message"),'width'=>'60px'], 
                 
     //                ];
     //    $dateTableFields = $columns;
        return view('shipper.pages.notification.index');
    }
}

?>

app/Http/Controllers/Shipper/ShipmentDesignController.php
<?php

namespace App\Http\Controllers\Shipper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Product;
use App\Models\TruckUnit;
use App\Models\Country;
use App\Models\Facility;
use App;

class ShipmentDesignController extends Controller
{
    public function create(){
    	return view ('shipper.pages.shipment.index');
    }

    public function designPage(){

    	return view ('shipper.pages.shipment.desing');
    }

    public function locations_sim(Request $request)
    {
        App::setLocale($request->lang);
        session()->put('locale', $request->lang);
        // dd($request->lang);sss
        $user = Auth::user();
        $products = Product::where('user_id', $user->id)->orderBy('id','desc')->get()->toArray();
        $unitData = TruckUnit::where('deleted_at',NULL)->get()->toArray();
        $country_pluck = Country::whereIn('name', ['Greece'])->pluck('id');
        $countries =  Country::whereIn('name', ['Greece'])->get();
        $addresses = Facility::where('user_id', $user->id)->select('*')->with('city_obj')->orderBy('id','desc')->get();
        $count = count($addresses);
        return view('shipper.pages.shipment.shipment_locations_sim', compact('products','unitData','countries','addresses','count'));
    }
}

resources/views/admin/pages/shipper/generate_invoice.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="page-title-box">
				<div class="page-title-right">
					{{ Breadcrumbs::render('shipper')}}
				</div>
				<h4 class="page-title">{{$invoiceTitle}}</h4>
			</div>
			
		</div>
	</div>
	  @include('admin.include.flash-message')
	<div class="row">
	
		<div class="col-xl-12">
			<div class="card">
				<div class="card-body table-responsive" >
					@include('admin.include.table')
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
@include('admin.include.table_script')
@endsection

resources/views/admin/pages/shipper/index.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="page-title-box">
				<div class="page-title-right">
					{{ Breadcrumbs::render('shipper')}}
				</div>
				<h4 class="page-title">{{$dateTableTitle}}</h4>
			</div>
			
		</div>
	</div>
	  @include('admin.include.flash-message')
	<div class="row">
	
		<div class="col-xl-12">
			<div class="card table-responsive">
				<div class="card-body">
					@include('admin.include.table')
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
@include('admin.include.table_script')
@endsection

resources/views/admin/pages/shipper/view_profile.blade.php
@extends('admin.layouts.master')
@section('content')
<link href="{{ url('shipper/css/dashboard.css') }}" rel="stylesheet" type="text/css" />
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="page-title-box">
				<div class="page-title-right">
					
				</div>
				<h4 class="page-title">{{$dateTableTitle}}</h4>
			</div>
		</div>
	</div>
	@include('admin.include.flash-message')
    <div class="row">
        <div class="col-lg-4 col-xl-4">
            <div class="card-box text-center">
                @if(isset($data->profile) && $data->profile != NULL && $data->profile != "")
                <img src="{{ env('S3_IMAGE_URL') }}shipper/{{$data->profile}}" class="rounded-circle avatar-lg img-thumbnail" alt="profile-image">
                @else
                <img src="{{ env('APP_URL') }}images/default.png" class="rounded-circle avatar-lg img-thumbnail" alt="profile-image">
                @endif
                <h4 class="mb-0">{{ $data->name }}</h4>
                <p class="text-muted">{{ $data->email }}</p>
                @if($data->status == 1)
                <button type="button" class="btn btn-success btn-xs waves-effect mb-2 waves-light" style="cursor: auto">Active</button>
                @else
                <button type="button" class="btn btn-danger btn-xs waves-effect mb-2 waves-light" style="cursor: auto">Inactive</button>
                @endif
                <div class="text-left mt-3">
                    {{-- <h4 class="font-13 text-uppercase">About Me :</h4>
                    <p class="text-muted font-13 mb-3">
                        {{ $data->self_des }}
                    </p> --}}
                    <p class="text-muted mb-2 font-13"><strong>Full Name :</strong> <span class="ml-2">
                     @if($data->first_name == NULL || $data->last_name == NULL) -- @else {{ $data->first_name }} {{ $data->last_name }} @endif </span></p>

                    <p class="text-muted mb-2 font-13"><strong>Mobile :</strong><span class="ml-2">@if($data->phone == NULL) -- @else {{ $data->phone }} @endif </span></p>

                    {{-- <p class="text-muted mb-2 font-13"><strong>Type :</strong> <span class="ml-2 ">{{ $data->type }}</span></p> --}}
                </div>
            </div> <!-- end card-box -->
        </div>
        <div class="col-lg-5 col-xl-5">
            <div class="card-box">
                <ul class="nav nav-pills navtab-bg nav-justified">
                    <li class="nav-item">
                        <a href="#settings" data-toggle="tab" aria-expanded="false" class="nav-link ">
                            Profile Update 
                        </a>
                    </li>
                </ul>
                <div class="tab-pane " id="settings">
                    <form method="post" enctype="multipart/form-data" action="{{route('admin.shipper.update', $data->id)}}">
                    @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="firstname">First Name</label>
                                    <input type="text" name="first_name"  parsley-trigger="change" required value="{{ $data->first_name }}" class="form-control" id="firstname" placeholder="Enter first name">
                                    @error('first_name')
                                        <div class="error">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <input type="text" parsley-trigger="change" required name="last_name"  value="{{ $data->last_name }}" class="form-control" id="last_name" placeholder="Enter last name">
                                    @error('last_name')
                                        <div class="error">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="useremail">Email Address</label>
                                    <input type="email" class="form-control" readonly id="useremail" value="{{ $data->email }}" placeholder="Enter email">
                                    
                                </div>
                            </div>
                        </div> <!-- end row -->

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="commission_fee">Commission Fee</label>
                                    <input type="text" name="commission_fee"  parsley-trigger="change" required value="{{ $data->commission_fee }}" class="form-control" id="commission_fee" placeholder="Enter commission fee">
                                    @error('commission_fee')
                                        <div class="error">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="phone">Phone No</label>
                                    <input type="call" parsley-trigger="change" required name="phone"  value="{{ $data->phone }}" class="form-control" id="phone" placeholder="Enter phone">
                                    @error('phone')
                                        <div class="error">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->

                        <div class="form-group">
                        <label for="useremail">Browse</label>

                            <div class="custom-file">
                                <input onchange="previewFile(this);"  type="file" class="custom-file-input" id="inputGroupFile01"
                                aria-describedby="inputGroupFileAddon01"  name="profile" parsley-trigger="change" value="{{old('profile')}}"  placeholder="Upload image" class="form-control" id="name">
                                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                
                            </div>
                            @error('name')
                                <div class="error">{{ $message }}</div>
                            @enderror
                        </div><br>
                      

                        <img id="previewImg" @if($data->profile != "") src="{{ env('S3_IMAGE_URL')}}shipper/{{ $data->profile }}" style="height: 100px;width: auto; display: block;" @else src=""  alt="Placeholder" style="height: 100px;width: auto; display: none;"  @endif>

                        <div class="text-right">
                            <button type="submit" class="btn btn-success waves-effect waves-light mt-2"><i class="mdi mdi-content-save"></i> Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection