routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SystemConfigController;
use App\Http\Controllers\Admin\PackageTypeController;
use App\Http\Controllers\Admin\TruckController;
use App\Http\Controllers\Admin\TruckTypeController;
use App\Http\Controllers\Admin\ShipperController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\BookingController;
use App\Http\Controllers\Admin\TruckUnitController;
use App\Http\Controllers\Shipper\AddressController;
use App\Http\Controllers\Shipper\AuthController;
use App\Http\Controllers\Shipper\DasboardController;
use App\Http\Controllers\Shipper\ProductController;
use App\Http\Controllers\Shipper\ShipmentController;
use App\Http\Controllers\Shipper\MultipleShipmentController;
use App\Http\Controllers\Shipper\ShipmentDesignController;
use App\Http\Controllers\Shipper\ManageShipmentController;
use App\Http\Controllers\Shipper\SearchAvailableTruckController;
use App\Http\Controllers\Shipper\ManagerManagementController;
use App\Http\Controllers\Shipper\ChatController;
use App\Http\Controllers\Shipper\DahsboardNewController;
use App\Http\Controllers\Shipper\NotificationController;
use App\Http\Controllers\Shipper\InvoiceController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\Carrier\DriverController as CarrierDriverController;
use App\Http\Controllers\Carrier\VehicleController;
use App\Http\Controllers\Carrier\CarrierAuthController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::POST('send-mail/{id}',[ShipperController::class,'send_mail']);
Route::POST('driver_send_mail/{id}',[DriverController::class,'driver_send_mail']);
Route::get('shipper-comission/{key}',[InvoiceController::class, 'shipperCommisionInvoice']);

Route::get('/', function () {
    return view('home');
});
Route::get('testData',[DashboardController::class,'testData']);
Route::get('/carrier', function () {
    return view('carrier');
});

Route::get('/shipper-demo', function () {
    return view('shipper');
});
Route::get('/terms-and-conditions', function () {
	    return view('terms_conditions');
	});
Route::get('/privacy-policy', function () {
	    return view('privacy_policy');
	});
Route::get('/about-us', function () {
	    return view('about-us');
	});
Route::get('change/lang/{lang}',[WebsiteController::class, 'changeLang'])->name('change-lang');

Route::get('cron-availability-trash',[AuthController::class, 'cron_past_availability'])->name('cron-availability-trash');
Route::get('cron-booking-trash',[AuthController::class, 'cron_past_booking'])->name('cron-booking-trash');
Route::get('cron-scheduled-booking-trash',[AuthController::class, 'cron_past_booking_scheduled'])->name('cron-scheduled-booking-trash');
// Route::get('/', function(){
// 	return view('shipper.pages.home');
// });
Route::get('/privacy-policy',[DashboardController::class,'get_privacy']);
	Route::get('/terms-condition',[DashboardController::class,'get_terms_condition']);
	Route::get('/about-us',[DashboardController::class,'get_about']);
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard');
	Route::get('terms_condition',[DashboardController::class,'terms_condition_index'])->name('terms_condition');
	Route::post('terms_condition/submit',[DashboardController::class,'terms_condition'])->name('terms_condition.submit');
	Route::get('about_us',[DashboardController::class,'about_us_index'])->name('about_us');
	Route::get('about_us/submit',[DashboardController::class,'about_us'])->name('about_us.submit');
	Route::get('my_profile',[DashboardController::class,'my_profile'])->name('my_profile');
	
	
	Route::get('privacy_policy',[DashboardController::class,'privacy_policy_index'])->name('privacy_policy');
	Route::post('privacy_policy/submit',[DashboardController::class,'privacy_policy'])->name('privacy_policy.submit');

	Route::get('dashboard/chart',[DashboardController::class,'chart']);
	Route::post('status/change/{table}/{id}/{newstatus}', [DashboardController::class,'status'])->name('status');
	

	Route::get('users',[UserController::class,'index'])->name('users.index');
	
	Route::get('system/config',[SystemConfigController::class,'index'])->name('system.config');
	Route::post('system/config/submit',[SystemConfigController::class,'update'])->name('system.config.submit');
	Route::get('app/config',[SystemConfigController::class,'app'])->name('app.config');
	Route::post('app/config/submit',[SystemConfigController::class,'submit_app'])->name('app.config.submit');
	Route::get('system/section',[SystemConfigController::class,'index_system']);
	

	#PACKAGE_TYPE
	Route::group(['prefix' => 'package/type'], function () {
		Route::get('/{id?}', [PackageTypeController::class,'index'])->name('package.type.index');
		Route::post('submit', [PackageTypeController::class,'store'])->name('package.type.submit');
		Route::get('edit/{id}', [PackageTypeController::class,'edit'])->name('package.type.edit');
		Route::post('update/{id}', [PackageTypeController::class,'update'])->name('package.type.update');
		Route::delete('delete/{id}', [PackageTypeController::class,'destroy'])->name('package.type.delete');
	});

	#PRODUCT_UNIT
	Route::group(['prefix' => 'truck/unit'], function () {
		Route::get('/{id?}', [TruckUnitController::class,'index'])->name('truck.unit.index');
		Route::post('submit', [TruckUnitController::class,'store'])->name('truck.unit.submit');
		Route::get('edit/{id}', [TruckUnitController::class,'edit'])->name('truck.unit.edit');
		Route::post('update/{id}', [TruckUnitController::class,'update'])->name('truck.unit.update');
		Route::delete('delete/{id}', [TruckUnitController::class,'destroy'])->name('truck.unit.delete');
	});

	#TRUCK_CATEGORY
	Route::group(['prefix' => 'truck/category'], function () {
		Route::get('/{id?}', [TruckController::class,'index'])->name('truck.category.index');
		Route::post('submit', [TruckController::class,'store'])->name('truck.category.submit');
		Route::get('edit/{id}', [TruckController::class,'edit'])->name('truck.category.edit');
		Route::post('update/{id}', [TruckController::class,'update'])->name('truck.category.update');
		Route::delete('delete/{id}', [TruckController::class,'destroy'])->name('truck.category.delete');
		
	});

	#TRUCK_TYPE
	Route::group(['prefix' => 'truck/type'], function () {
		Route::get('/{id?}', [TruckTypeController::class,'index'])->name('truck.type.index');
		Route::post('submit', [TruckTypeController::class,'store'])->name('truck.type.submit');
		Route::get('edit/{id}', [TruckTypeController::class,'edit'])->name('truck.type.edit');
		Route::post('update/{id}', [TruckTypeController::class,'update'])->name('truck.type.update');
		Route::delete('delete/{id}', [TruckTypeController::class,'destroy'])->name('truck.type.delete');
		
	});

	#SHIPPER
	Route::group(['prefix' => 'shipper'], function(){
		Route::get('/', [ShipperController::class,'index'])->name('shipper.index');
		Route::get('view/{id}', [ShipperController::class,'view'])->name('shipper.view');
		Route::post('update/{id}', [ShipperController::class,'update'])->name('shipper.update');
		Route::post('approve/{id}/{status}', [ShipperController::class,'approveStatus'])->name('shipper.approve.status');
		Route::get('shipment/{id}', [ShipperController::class,'shipment']);
		Route::get('shipment_demo/{id}', [ShipperController::class,'demo_shipment']);
		Route::get('shipment-comm/{id}', [ShipperController::class,'commission_fee']);
		// Route::get('generate_invoice', [ShipperController::class,'generate_invoice']);
		Route::get('generate-invoice/{id}', [ShipperController::class,'get_invoice']);
		Route::get('view_profile/{id}', [ShipperController::class,'view_profile'])->name('shipper.view_profile');
		Route::get('shipment-detail/{id}', [ShipperController::class,'shipment_detail']);
		Route::get('shipment-search/{id}', [ShipperController::class,'shipment_search']);
		Route::post('shipment-search/public/{id}', [ShipperController::class,'publish_shipment']);
	});

	#DRIVER
	Route::group(['prefix' => 'driver'], function(){
		Route::get('/', [DriverController::class,'index'])->name('driver.index'); 
		Route::get('view/{id}', [DriverController::class,'view'])->name('driver.view');
		Route::get('view_load/{id}', [DriverController::class,'view_load'])->name('driver.view_load');
		Route::get('generate_invoice/{id}', [DriverController::class,'get_invoice']);
		// Route::get('view_load/{id}', [DriverController::class,'my_loads_demo'])->name('driver.my_loads_demo');
		Route::get('view_profile/{id}', [DriverController::class,'view_profile'])->name('shipper.view_profile');
		Route::post('update/{id}', [DriverController::class,'update'])->name('driver.update');
		Route::post('accept/{id}', [DriverController::class,'accepted'])->name('driver.accepted');
		Route::post('reject/{id}', [DriverController::class,'rejected'])->name('driver.rejected');
		Route::post('block/{id}/{status}', [DriverController::class,'blockStatus'])->name('driver.block.status');
		Route::post('change-permissions/{id}', [DriverController::class,'change_permission'])->name('driver.change-permissions');
		
	});

	#BOOKING
	Route::group(['prefix' => 'booking'], function(){
		Route::get('/', [BookingController::class,'index'])->name('booking.index'); 
		Route::delete('delete/{id}', [BookingController::class,'destroy'])->name('booking.delete');
		// Route::get('view/{id}', [DriverController::class,'view'])->name('driver.view');

resources/views/admin/pages/truck_type/index.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="page-title-box">
				<div class="page-title-right">
					{{ Breadcrumbs::render('truck')}}
				</div>
				<h4 class="page-title">{{$dateTableTitle}}</h4>
			</div>
			
		</div>
	</div>
	  @include('admin.include.flash-message')
	<div class="row">
		<div class="col-xl-4">
			<div class="card">
				<div class="card-body table-responsive">
                @if(isset($edit_param) && $edit_param != null)
                    <h4 class="header-title mb-2">Edit Truck Type</h4>
					<form method="post" enctype="multipart/form-data" action="{{ route('admin.truck.type.update', $edit_param->id )}}">
						@csrf
                       
						<div class="form-group">
							<label for="name">Truck Type <span class="text-danger">*</span></label>
							<input type="text" maxlength="20" name="name" parsley-trigger="change" value="{{ $edit_param->name }}" required placeholder="Enter Type" class="form-control" id="name">
							@error('name')
							<div class="error">{{ $message }}</div>
							@enderror
						</div>
                        
                        <div class="form-group">
                            <label for="name">Truck Unit<span class="text-danger">*</span></label>
                            <select name="truck_unit" class="form-control select2">
                                @if(!empty($truck_unit) )
                                @foreach ($truck_unit as $truckunit)
                                <option value="{{ $truckunit['id'] }}">{{ $truckunit['name'] }}</option>
                                @endforeach
                                @endif
                            </select>
						</div>

                        <div class="form-group">
							<label for="name">Capacity<span class="text-danger">*</span></label>
							<input type="text" maxlength="20" name="capacity" parsley-trigger="change"  value="{{ $edit_param->capacity }}" required placeholder="Capacity" class="form-control" id="name">
						</div>
						<div class="form-group">
							<label for="is_trailer">Is Trailer</label>
							<input type="checkbox" id="is_trailer" style="margin-left: 5px;" name="is_trailer" value="1" {{ $edit_param->is_trailer ? 'checked' : '' }}>
						</div>

						<div class="form-group">
							
							<div class="custom-file">
								<input type="file" class="custom-file-input" id="inputGroupFile01"
								aria-describedby="inputGroupFileAddon01"  id="customFile" name="image" parsley-trigger="change" value="{{old('image')}}"  placeholder="Upload image" class="form-control" id="name">
								<label class="custom-file-label" for="inputGroupFile01">Choose file</label>
								
							</div>
						</div><br>
						@error('name')
						<div class="error">{{ $message }}</div>
						@enderror
						<img src="{{ $base }}/{{ $edit_param->icon}}" class="oldimg" style="height: 50%;width: 30%;"/> 

                      
                      

						<div class="form-group text-right m-b-0">
							<button class="btn btn-primary waves-effect waves-light" type="submit">
							Submit
							</button>
							<button type="reset" onclick="return reset();" class="btn btn-secondary waves-effect m-l-5">
							Reset
							</button>
						</div>
					</form>

               @else

                    <h4 class="header-title mb-2">Add Truck Type</h4>
					<form method="post" enctype="multipart/form-data" action="{{route('admin.truck.type.submit')}}">
						@csrf

                        
						<div class="form-group">
							<label for="name">Truck Type <span class="text-danger">*</span></label>
							<input type="text" maxlength="20" name="name" parsley-trigger="change" value="{{old('name')}}" required placeholder="Enter Type" class="form-control" id="name">
							@error('name')
							<div class="error">{{ $message }}</div>
							@enderror
						</div>

                       <div class="form-group">
                            <label for="type">Truck Unit<span class="text-danger">*</span></label>
                            <select data-parsley-required="true" data-parsley-required-message="This value is required."
                            class="form-control data-parsley-validate-if-empty select2" parsley-trigger="change" id="type" name="truck_unit" >
                                @if(!empty($truck_unit))
                                <option value="" disabled selected>Truck Unit</option>
                                @foreach ($truck_unit as $truckunit)

                                <option value="{{ $truckunit['id'] }}">{{ $truckunit['name'] }}</option>
                                @endforeach
                                @endif
                            </select>
                        </div>
                        

                        <div class="form-group">
							<label for="name">Capacity<span class="text-danger">*</span></label>
							<input type="text" maxlength="20" name="capacity" parsley-trigger="change" value="{{old('name')}}" required placeholder="Capacity" class="form-control" id="name">
						</div>
						<div class="form-group">
							<label for="is_trailer">Is Trailer</label>
							<input type="checkbox" id="is_trailer" style="margin-left: 5px;" name="is_trailer" value="1">
						</div>

						<div class="form-group">
							
							<div class="custom-file">
								<input onchange="previewFile(this);"  type="file" class="custom-file-input" id="inputGroupFile01"
								aria-describedby="inputGroupFileAddon01"  name="image" parsley-trigger="change" value="{{old('image')}}" required placeholder="Upload image" class="form-control" id="name" data-parsley-required-message="Please select truck type image">
								<label class="custom-file-label" for="inputGroupFile01">Choose file</label>
								
							</div>
						</div>
						

						<img id="previewImg" src="" style="height: 100px;width: auto; display: none;">

						


						<div class="form-group text-right m-b-0">
							<button class="btn btn-primary waves-effect waves-light" type="submit">
							Submit
							</button>
							<button type="reset" onclick="return reset();" class="btn btn-secondary waves-effect m-l-5">
							Reset
							</button>
						</div>
					</form>

                @endif

					
				</div>
			</div>
		</div>

		<div class="col-xl-8">
			<div class="card">
				<div class="card-body table-responsive" >
					@include('admin.include.table')
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
@include('admin.include.table_script')


@endsection